      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_NICE_DUNE_046EB4910 }}
          action: "upload"
          app_location: "/"
          api_location: ""
          output_location: ""
          app_build_command: ""
          github_id_token: ${{ steps.idtoken.outputs.result }}
